#!/usr/bin/env bash
# (ensure we pull bash from path not /usr/bin)
set -e

if git status --porcelain | grep -q '^[ M]'
then
   echo "Locally modified files. Stash or discard before pushing."
   exit 1
else
   echo "No locally modified files. Checking format."
   yarn workspace @fluid-org/fluid tidy
   if git status --porcelain | grep -q '^[ M]'
   then
      echo "Format fixed. Commit again before pushing."
      exit 1
   fi
   echo "Format OK. Strict build (catches unused imports)."
   yarn workspace @fluid-org/fluid build-strict
   echo "Pushing."
fi
