yarnPath: .yarn/releases/yarn-4.12.0.cjs
nodeLinker: node-modules

npmRegistries:
  "https://registry.yarnpkg.com":
    npmAuthToken: "${NPM_TOKEN}"
  "https://registry.npmjs.org":
    npmAuthToken: "${NPM_TOKEN}"

npmPublishRegistry: "https://registry.npmjs.org"
