const rowListSetImpl = dictTypeEquals => dictTypeEquals1 => () => ({});
const rowListRemoveNil = {};
const rowListRemoveCons = () => () => () => ({});
const rowListNubNil = {};
const rowListNubCons = dictTypeEquals => dictTypeEquals1 => dictTypeEquals2 => () => () => ({});
const rowListAppendNil = dictTypeEquals => ({});
const rowListAppendCons = () => dictTypeEquals => ({});
const listToRowNil = {};
const listToRowCons = () => () => ({});
export {listToRowCons, listToRowNil, rowListAppendCons, rowListAppendNil, rowListNubCons, rowListNubNil, rowListRemoveCons, rowListRemoveNil, rowListSetImpl};
