import * as Unsafe$dCoerce from "../Unsafe.Coerce/index.js";
import * as Web$dInternal$dFFI from "../Web.Internal.FFI/index.js";
const toParentNode = Unsafe$dCoerce.unsafeCoerce;
const toNonElementParentNode = Unsafe$dCoerce.unsafeCoerce;
const toNode = Unsafe$dCoerce.unsafeCoerce;
const toEventTarget = Unsafe$dCoerce.unsafeCoerce;
const toChildNode = Unsafe$dCoerce.unsafeCoerce;
const fromParentNode = /* #__PURE__ */ Web$dInternal$dFFI.unsafeReadProtoTagged("DocumentFragment");
const fromNonElementParentNode = /* #__PURE__ */ Web$dInternal$dFFI.unsafeReadProtoTagged("DocumentFragment");
const fromNode = /* #__PURE__ */ Web$dInternal$dFFI.unsafeReadProtoTagged("DocumentFragment");
const fromEventTarget = /* #__PURE__ */ Web$dInternal$dFFI.unsafeReadProtoTagged("DocumentFragment");
const fromChildNode = /* #__PURE__ */ Web$dInternal$dFFI.unsafeReadProtoTagged("DocumentFragment");
export {fromChildNode, fromEventTarget, fromNode, fromNonElementParentNode, fromParentNode, toChildNode, toEventTarget, toNode, toNonElementParentNode, toParentNode};
