import * as Unsafe$dCoerce from "../Unsafe.Coerce/index.js";
import * as Web$dInternal$dFFI from "../Web.Internal.FFI/index.js";
const toNonDocumentTypeChildNode = Unsafe$dCoerce.unsafeCoerce;
const toNode = Unsafe$dCoerce.unsafeCoerce;
const toEventTarget = Unsafe$dCoerce.unsafeCoerce;
const toChildNode = Unsafe$dCoerce.unsafeCoerce;
const toCharacterData = Unsafe$dCoerce.unsafeCoerce;
const fromNonDocumentTypeChildNode = /* #__PURE__ */ Web$dInternal$dFFI.unsafeReadProtoTagged("Comment");
const fromNode = /* #__PURE__ */ Web$dInternal$dFFI.unsafeReadProtoTagged("Comment");
const fromEventTarget = /* #__PURE__ */ Web$dInternal$dFFI.unsafeReadProtoTagged("Comment");
const fromChildNode = /* #__PURE__ */ Web$dInternal$dFFI.unsafeReadProtoTagged("Comment");
const fromCharacterData = /* #__PURE__ */ Web$dInternal$dFFI.unsafeReadProtoTagged("Comment");
export {fromCharacterData, fromChildNode, fromEventTarget, fromNode, fromNonDocumentTypeChildNode, toCharacterData, toChildNode, toEventTarget, toNode, toNonDocumentTypeChildNode};
