import * as Unsafe$dCoerce from "../Unsafe.Coerce/index.js";
import * as Web$dInternal$dFFI from "../Web.Internal.FFI/index.js";
import {target} from "./foreign.js";
const toNonDocumentTypeChildNode = Unsafe$dCoerce.unsafeCoerce;
const toNode = Unsafe$dCoerce.unsafeCoerce;
const toEventTarget = Unsafe$dCoerce.unsafeCoerce;
const toChildNode = Unsafe$dCoerce.unsafeCoerce;
const toCharacterData = Unsafe$dCoerce.unsafeCoerce;
const fromNonDocumentTypeChildNode = /* #__PURE__ */ Web$dInternal$dFFI.unsafeReadProtoTagged("ProcessingInstruction");
const fromNode = /* #__PURE__ */ Web$dInternal$dFFI.unsafeReadProtoTagged("ProcessingInstruction");
const fromEventTarget = /* #__PURE__ */ Web$dInternal$dFFI.unsafeReadProtoTagged("ProcessingInstruction");
const fromChildNode = /* #__PURE__ */ Web$dInternal$dFFI.unsafeReadProtoTagged("ProcessingInstruction");
const fromCharacterData = /* #__PURE__ */ Web$dInternal$dFFI.unsafeReadProtoTagged("ProcessingInstruction");
export {fromCharacterData, fromChildNode, fromEventTarget, fromNode, fromNonDocumentTypeChildNode, toCharacterData, toChildNode, toEventTarget, toNode, toNonDocumentTypeChildNode};
export * from "./foreign.js";
