// Generated automatically by nearley, version 2.16.0
// http://github.com/Hardmath123/nearley
// Bypasses TS6133. Allow declared but unused functions.
// @ts-ignore
function id(d: any[]): any { return d[0]; }
declare var whitespace: any;
declare var singleLineComment: any;
declare var ident: any;
declare var string: any;
declare var number: any;
declare var compareOp: any;
declare var exponentOp: any;
declare var productOp: any;
declare var sumOp: any;

const moo = require('moo')
const lexer = moo.compile({
   ident: {
      match: /[a-zA-Z_][0-9a-zA-Z_]*/, // greedy
      type: moo.keywords({
        keyword: ["as", "match", "fun", "in", "let", "letrec", "primitive", "typematch"],
      })
   },
   whitespace: {
      match: /[ \f\t\r\n]+/,
      lineBreaks: true
   },
   singleLineComment: /\/\/.*$/,
   // WIP: JSON grammar for numbers, https://tools.ietf.org/html/rfc7159.html#section-6.
   number: /0|[1-9][0-9]*/,
   string: /"(?:\\["\\]|[^\n"\\])*"/,
   // not quite sure why I can't use literals here:
   sumOp: /\-|\+\+|\+/,
   productOp: /\*|\//,
   exponentOp: /\*\*/,
   compareOp: /===|==|<==|<=|<|>==|>=|>/,
   symbol: ["(", ")", "=", "→", ";", "{", "}", ",", "[", "]", "..."], // needs to come after compareOp
})


import { Expr } from "./Expr"
import { ν, num, str } from "./Versioned"

export interface Token { value: any; [key: string]: any };

export interface Lexer {
  reset: (chunk: string, info: any) => void;
  next: () => Token | undefined;
  save: () => any;
  formatError: (token: Token) => string;
  has: (tokenType: string) => boolean
};

export interface NearleyRule {
  name: string;
  symbols: NearleySymbol[];
  postprocess?: (d: any[], loc?: number, reject?: {}) => any
};

export type NearleySymbol = string | { literal: any } | { test: (token: any) => boolean };

export var Lexer: Lexer | undefined = lexer;

export var ParserRules: NearleyRule[] = [
    {"name": "rootExpr", "symbols": ["_", "expr"], "postprocess": ([, e]) => e},
    {"name": "rootExpr", "symbols": ["expr"], "postprocess": id},
    {"name": "_$ebnf$1$subexpression$1", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)]},
    {"name": "_$ebnf$1$subexpression$1", "symbols": [(lexer.has("singleLineComment") ? {type: "singleLineComment"} : singleLineComment)]},
    {"name": "_$ebnf$1", "symbols": ["_$ebnf$1$subexpression$1"]},
    {"name": "_$ebnf$1$subexpression$2", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)]},
    {"name": "_$ebnf$1$subexpression$2", "symbols": [(lexer.has("singleLineComment") ? {type: "singleLineComment"} : singleLineComment)]},
    {"name": "_$ebnf$1", "symbols": ["_$ebnf$1", "_$ebnf$1$subexpression$2"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "_", "symbols": ["_$ebnf$1"]},
    {"name": "expr", "symbols": ["compareExpr"], "postprocess": id},
    {"name": "expr", "symbols": ["defs1"], "postprocess": id},
    {"name": "defs1$macrocall$2", "symbols": [{"literal":"in"}]},
    {"name": "defs1$macrocall$1$macrocall$2", "symbols": ["defs1$macrocall$2"]},
    {"name": "defs1$macrocall$1$macrocall$1", "symbols": ["defs1$macrocall$1$macrocall$2"], "postprocess": id},
    {"name": "defs1$macrocall$1$macrocall$1", "symbols": ["defs1$macrocall$1$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "defs1$macrocall$1", "symbols": ["defs1$macrocall$1$macrocall$1"]},
    {"name": "defs1", "symbols": ["defList", "defs1$macrocall$1", "expr"], "postprocess": ([defs, , e]) => Expr.defs(ν(), defs, e)},
    {"name": "compareExpr", "symbols": ["compareExpr", "compareOp", "sumExpr"], "postprocess": ([e1, op, e2]) => Expr.binaryApp(ν(), e1, str(ν(), op), e2)},
    {"name": "compareExpr", "symbols": ["sumExpr"], "postprocess": id},
    {"name": "sumExpr", "symbols": ["sumExpr", "sumOp", "productExpr"], "postprocess": ([e1, op, e2]) => Expr.binaryApp(ν(), e1, str(ν(), op), e2)},
    {"name": "sumExpr", "symbols": ["productExpr"], "postprocess": id},
    {"name": "productExpr", "symbols": ["productExpr", "productOp", "exponentExpr"], "postprocess": ([e1, op, e2]) => Expr.binaryApp(ν(), e1, str(ν(), op), e2)},
    {"name": "productExpr", "symbols": ["exponentExpr"], "postprocess": id},
    {"name": "exponentExpr", "symbols": ["exponentExpr", "exponentOp", "appChain"], "postprocess": ([e1, op, e2]) => Expr.binaryApp(ν(), e1, str(ν(), op), e2)},
    {"name": "exponentExpr", "symbols": ["appChain"], "postprocess": id},
    {"name": "appChain", "symbols": ["simpleExpr"], "postprocess": id},
    {"name": "appChain", "symbols": ["appChain", "simpleExpr"], "postprocess": ([e1, e2]) => Expr.app(ν(), e1, e2)},
    {"name": "simpleExpr", "symbols": ["variable"], "postprocess": id},
    {"name": "simpleExpr", "symbols": ["string"], "postprocess": id},
    {"name": "simpleExpr", "symbols": ["number"], "postprocess": id},
    {"name": "simpleExpr", "symbols": ["parenthExpr"], "postprocess": id},
    {"name": "simpleExpr", "symbols": ["pair"], "postprocess": id},
    {"name": "simpleExpr", "symbols": ["list"], "postprocess": id},
    {"name": "simpleExpr", "symbols": ["matchAs"], "postprocess": id},
    {"name": "simpleExpr", "symbols": ["fun"], "postprocess": id},
    {"name": "simpleExpr", "symbols": ["typematch"], "postprocess": id},
    {"name": "variable", "symbols": ["var"], "postprocess": ([x]) => Expr.var_(ν(), x)},
    {"name": "var$macrocall$2", "symbols": [(lexer.has("ident") ? {type: "ident"} : ident)]},
    {"name": "var$macrocall$1", "symbols": ["var$macrocall$2"], "postprocess": id},
    {"name": "var$macrocall$1", "symbols": ["var$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "var", "symbols": ["var$macrocall$1"], "postprocess": ([x]) => str(ν(), x as string)},
    {"name": "string$macrocall$2", "symbols": [(lexer.has("string") ? {type: "string"} : string)]},
    {"name": "string$macrocall$1", "symbols": ["string$macrocall$2"], "postprocess": id},
    {"name": "string$macrocall$1", "symbols": ["string$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "string", "symbols": ["string$macrocall$1"], "postprocess": ([lit]) => Expr.constStr(ν(), str(ν(), lit as string))},
    {"name": "number$macrocall$2", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "number$macrocall$1", "symbols": ["number$macrocall$2"], "postprocess": id},
    {"name": "number$macrocall$1", "symbols": ["number$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "number", "symbols": ["number$macrocall$1"], "postprocess": ([lit]) => Expr.constNum(ν(), num(ν(), new Number(lit as string).valueOf()))},
    {"name": "parenthExpr$macrocall$2", "symbols": [{"literal":"("}]},
    {"name": "parenthExpr$macrocall$1", "symbols": ["parenthExpr$macrocall$2"], "postprocess": id},
    {"name": "parenthExpr$macrocall$1", "symbols": ["parenthExpr$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "parenthExpr$macrocall$4", "symbols": [{"literal":")"}]},
    {"name": "parenthExpr$macrocall$3", "symbols": ["parenthExpr$macrocall$4"], "postprocess": id},
    {"name": "parenthExpr$macrocall$3", "symbols": ["parenthExpr$macrocall$4", "_"], "postprocess": ([x, ]) => x},
    {"name": "parenthExpr", "symbols": ["parenthExpr$macrocall$1", "expr", "parenthExpr$macrocall$3"], "postprocess": ([, e,]) => e},
    {"name": "pair$macrocall$2", "symbols": [{"literal":"("}]},
    {"name": "pair$macrocall$1", "symbols": ["pair$macrocall$2"], "postprocess": id},
    {"name": "pair$macrocall$1", "symbols": ["pair$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "pair$macrocall$4", "symbols": [{"literal":","}]},
    {"name": "pair$macrocall$3", "symbols": ["pair$macrocall$4"], "postprocess": id},
    {"name": "pair$macrocall$3", "symbols": ["pair$macrocall$4", "_"], "postprocess": ([x, ]) => x},
    {"name": "pair$macrocall$6", "symbols": [{"literal":")"}]},
    {"name": "pair$macrocall$5", "symbols": ["pair$macrocall$6"], "postprocess": id},
    {"name": "pair$macrocall$5", "symbols": ["pair$macrocall$6", "_"], "postprocess": ([x, ]) => x},
    {"name": "pair", "symbols": ["pair$macrocall$1", "expr", "pair$macrocall$3", "expr", "pair$macrocall$5"]},
    {"name": "list$macrocall$2", "symbols": [{"literal":"["}]},
    {"name": "list$macrocall$1", "symbols": ["list$macrocall$2"], "postprocess": id},
    {"name": "list$macrocall$1", "symbols": ["list$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "list$macrocall$4", "symbols": [{"literal":"]"}]},
    {"name": "list$macrocall$3", "symbols": ["list$macrocall$4"], "postprocess": id},
    {"name": "list$macrocall$3", "symbols": ["list$macrocall$4", "_"], "postprocess": ([x, ]) => x},
    {"name": "list", "symbols": ["list$macrocall$1", "listOpt", "list$macrocall$3"]},
    {"name": "typematch$macrocall$2", "symbols": [{"literal":"typematch"}]},
    {"name": "typematch$macrocall$1$macrocall$2", "symbols": ["typematch$macrocall$2"]},
    {"name": "typematch$macrocall$1$macrocall$1", "symbols": ["typematch$macrocall$1$macrocall$2"], "postprocess": id},
    {"name": "typematch$macrocall$1$macrocall$1", "symbols": ["typematch$macrocall$1$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "typematch$macrocall$1", "symbols": ["typematch$macrocall$1$macrocall$1"]},
    {"name": "typematch$macrocall$4", "symbols": [{"literal":"as"}]},
    {"name": "typematch$macrocall$3$macrocall$2", "symbols": ["typematch$macrocall$4"]},
    {"name": "typematch$macrocall$3$macrocall$1", "symbols": ["typematch$macrocall$3$macrocall$2"], "postprocess": id},
    {"name": "typematch$macrocall$3$macrocall$1", "symbols": ["typematch$macrocall$3$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "typematch$macrocall$3", "symbols": ["typematch$macrocall$3$macrocall$1"]},
    {"name": "typematch", "symbols": ["typematch$macrocall$1", "expr", "typematch$macrocall$3", "typeMatches"]},
    {"name": "defList$ebnf$1", "symbols": []},
    {"name": "defList$ebnf$1$subexpression$1$macrocall$2", "symbols": [{"literal":";"}]},
    {"name": "defList$ebnf$1$subexpression$1$macrocall$1", "symbols": ["defList$ebnf$1$subexpression$1$macrocall$2"], "postprocess": id},
    {"name": "defList$ebnf$1$subexpression$1$macrocall$1", "symbols": ["defList$ebnf$1$subexpression$1$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "defList$ebnf$1$subexpression$1", "symbols": ["defList$ebnf$1$subexpression$1$macrocall$1", "def"], "postprocess": ([, def]) => def},
    {"name": "defList$ebnf$1", "symbols": ["defList$ebnf$1", "defList$ebnf$1$subexpression$1"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "defList", "symbols": ["def", "defList$ebnf$1"], "postprocess": ([def, defs]) => { defs.unshift(def); return defs }},
    {"name": "def", "symbols": ["let"], "postprocess": id},
    {"name": "def", "symbols": ["letrec"], "postprocess": id},
    {"name": "def", "symbols": ["prim"], "postprocess": id},
    {"name": "let$macrocall$2", "symbols": [{"literal":"let"}]},
    {"name": "let$macrocall$1$macrocall$2", "symbols": ["let$macrocall$2"]},
    {"name": "let$macrocall$1$macrocall$1", "symbols": ["let$macrocall$1$macrocall$2"], "postprocess": id},
    {"name": "let$macrocall$1$macrocall$1", "symbols": ["let$macrocall$1$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "let$macrocall$1", "symbols": ["let$macrocall$1$macrocall$1"]},
    {"name": "let$macrocall$4", "symbols": [{"literal":"="}]},
    {"name": "let$macrocall$3", "symbols": ["let$macrocall$4"], "postprocess": id},
    {"name": "let$macrocall$3", "symbols": ["let$macrocall$4", "_"], "postprocess": ([x, ]) => x},
    {"name": "let", "symbols": ["let$macrocall$1", "var", "let$macrocall$3", "expr"], "postprocess": ([, x, , e]) => Expr.let_(x, e)},
    {"name": "letrec$macrocall$2", "symbols": [{"literal":"letrec"}]},
    {"name": "letrec$macrocall$1$macrocall$2", "symbols": ["letrec$macrocall$2"]},
    {"name": "letrec$macrocall$1$macrocall$1", "symbols": ["letrec$macrocall$1$macrocall$2"], "postprocess": id},
    {"name": "letrec$macrocall$1$macrocall$1", "symbols": ["letrec$macrocall$1$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "letrec$macrocall$1", "symbols": ["letrec$macrocall$1$macrocall$1"]},
    {"name": "letrec$ebnf$1", "symbols": []},
    {"name": "letrec$ebnf$1$subexpression$1$macrocall$2", "symbols": [{"literal":";"}]},
    {"name": "letrec$ebnf$1$subexpression$1$macrocall$1", "symbols": ["letrec$ebnf$1$subexpression$1$macrocall$2"], "postprocess": id},
    {"name": "letrec$ebnf$1$subexpression$1$macrocall$1", "symbols": ["letrec$ebnf$1$subexpression$1$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "letrec$ebnf$1$subexpression$1", "symbols": ["letrec$ebnf$1$subexpression$1$macrocall$1", "recDef"]},
    {"name": "letrec$ebnf$1", "symbols": ["letrec$ebnf$1", "letrec$ebnf$1$subexpression$1"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "letrec", "symbols": ["letrec$macrocall$1", "recDef", "letrec$ebnf$1"]},
    {"name": "recDef$macrocall$2", "symbols": [{"literal":"fun"}]},
    {"name": "recDef$macrocall$1$macrocall$2", "symbols": ["recDef$macrocall$2"]},
    {"name": "recDef$macrocall$1$macrocall$1", "symbols": ["recDef$macrocall$1$macrocall$2"], "postprocess": id},
    {"name": "recDef$macrocall$1$macrocall$1", "symbols": ["recDef$macrocall$1$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "recDef$macrocall$1", "symbols": ["recDef$macrocall$1$macrocall$1"]},
    {"name": "recDef", "symbols": ["recDef$macrocall$1", "var", "matches"]},
    {"name": "prim$macrocall$2", "symbols": [{"literal":"primitive"}]},
    {"name": "prim$macrocall$1$macrocall$2", "symbols": ["prim$macrocall$2"]},
    {"name": "prim$macrocall$1$macrocall$1", "symbols": ["prim$macrocall$1$macrocall$2"], "postprocess": id},
    {"name": "prim$macrocall$1$macrocall$1", "symbols": ["prim$macrocall$1$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "prim$macrocall$1", "symbols": ["prim$macrocall$1$macrocall$1"]},
    {"name": "prim", "symbols": ["prim$macrocall$1", "var"]},
    {"name": "fun$macrocall$2", "symbols": [{"literal":"fun"}]},
    {"name": "fun$macrocall$1$macrocall$2", "symbols": ["fun$macrocall$2"]},
    {"name": "fun$macrocall$1$macrocall$1", "symbols": ["fun$macrocall$1$macrocall$2"], "postprocess": id},
    {"name": "fun$macrocall$1$macrocall$1", "symbols": ["fun$macrocall$1$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "fun$macrocall$1", "symbols": ["fun$macrocall$1$macrocall$1"]},
    {"name": "fun", "symbols": ["fun$macrocall$1", "matches"]},
    {"name": "matchAs$macrocall$2", "symbols": [{"literal":"match"}]},
    {"name": "matchAs$macrocall$1$macrocall$2", "symbols": ["matchAs$macrocall$2"]},
    {"name": "matchAs$macrocall$1$macrocall$1", "symbols": ["matchAs$macrocall$1$macrocall$2"], "postprocess": id},
    {"name": "matchAs$macrocall$1$macrocall$1", "symbols": ["matchAs$macrocall$1$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "matchAs$macrocall$1", "symbols": ["matchAs$macrocall$1$macrocall$1"]},
    {"name": "matchAs$macrocall$4", "symbols": [{"literal":"as"}]},
    {"name": "matchAs$macrocall$3$macrocall$2", "symbols": ["matchAs$macrocall$4"]},
    {"name": "matchAs$macrocall$3$macrocall$1", "symbols": ["matchAs$macrocall$3$macrocall$2"], "postprocess": id},
    {"name": "matchAs$macrocall$3$macrocall$1", "symbols": ["matchAs$macrocall$3$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "matchAs$macrocall$3", "symbols": ["matchAs$macrocall$3$macrocall$1"]},
    {"name": "matchAs", "symbols": ["matchAs$macrocall$1", "expr", "matchAs$macrocall$3", "matches"]},
    {"name": "matches", "symbols": ["match"]},
    {"name": "matches$macrocall$2", "symbols": [{"literal":"{"}]},
    {"name": "matches$macrocall$1", "symbols": ["matches$macrocall$2"], "postprocess": id},
    {"name": "matches$macrocall$1", "symbols": ["matches$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "matches$ebnf$1", "symbols": []},
    {"name": "matches$ebnf$1$subexpression$1$macrocall$2", "symbols": [{"literal":";"}]},
    {"name": "matches$ebnf$1$subexpression$1$macrocall$1", "symbols": ["matches$ebnf$1$subexpression$1$macrocall$2"], "postprocess": id},
    {"name": "matches$ebnf$1$subexpression$1$macrocall$1", "symbols": ["matches$ebnf$1$subexpression$1$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "matches$ebnf$1$subexpression$1", "symbols": ["matches$ebnf$1$subexpression$1$macrocall$1", "match"]},
    {"name": "matches$ebnf$1", "symbols": ["matches$ebnf$1", "matches$ebnf$1$subexpression$1"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "matches$macrocall$4", "symbols": [{"literal":"}"}]},
    {"name": "matches$macrocall$3", "symbols": ["matches$macrocall$4"], "postprocess": id},
    {"name": "matches$macrocall$3", "symbols": ["matches$macrocall$4", "_"], "postprocess": ([x, ]) => x},
    {"name": "matches", "symbols": ["matches$macrocall$1", "match", "matches$ebnf$1", "matches$macrocall$3"]},
    {"name": "match$macrocall$2", "symbols": [{"literal":"→"}]},
    {"name": "match$macrocall$1", "symbols": ["match$macrocall$2"], "postprocess": id},
    {"name": "match$macrocall$1", "symbols": ["match$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "match", "symbols": ["pattern", "match$macrocall$1", "expr"]},
    {"name": "match", "symbols": ["pattern", "matches"]},
    {"name": "typeMatches", "symbols": ["typeMatch"]},
    {"name": "typeMatches$macrocall$2", "symbols": [{"literal":"{"}]},
    {"name": "typeMatches$macrocall$1", "symbols": ["typeMatches$macrocall$2"], "postprocess": id},
    {"name": "typeMatches$macrocall$1", "symbols": ["typeMatches$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "typeMatches$ebnf$1", "symbols": []},
    {"name": "typeMatches$ebnf$1$subexpression$1$macrocall$2", "symbols": [{"literal":";"}]},
    {"name": "typeMatches$ebnf$1$subexpression$1$macrocall$1", "symbols": ["typeMatches$ebnf$1$subexpression$1$macrocall$2"], "postprocess": id},
    {"name": "typeMatches$ebnf$1$subexpression$1$macrocall$1", "symbols": ["typeMatches$ebnf$1$subexpression$1$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "typeMatches$ebnf$1$subexpression$1", "symbols": ["typeMatches$ebnf$1$subexpression$1$macrocall$1", "typeMatch"]},
    {"name": "typeMatches$ebnf$1", "symbols": ["typeMatches$ebnf$1", "typeMatches$ebnf$1$subexpression$1"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "typeMatches$macrocall$4", "symbols": [{"literal":"}"}]},
    {"name": "typeMatches$macrocall$3", "symbols": ["typeMatches$macrocall$4"], "postprocess": id},
    {"name": "typeMatches$macrocall$3", "symbols": ["typeMatches$macrocall$4", "_"], "postprocess": ([x, ]) => x},
    {"name": "typeMatches", "symbols": ["typeMatches$macrocall$1", "typeMatch", "typeMatches$ebnf$1", "typeMatches$macrocall$3"]},
    {"name": "typeMatch$macrocall$2", "symbols": [(lexer.has("ident") ? {type: "ident"} : ident)]},
    {"name": "typeMatch$macrocall$1", "symbols": ["typeMatch$macrocall$2"], "postprocess": id},
    {"name": "typeMatch$macrocall$1", "symbols": ["typeMatch$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "typeMatch$macrocall$4", "symbols": [{"literal":"→"}]},
    {"name": "typeMatch$macrocall$3", "symbols": ["typeMatch$macrocall$4"], "postprocess": id},
    {"name": "typeMatch$macrocall$3", "symbols": ["typeMatch$macrocall$4", "_"], "postprocess": ([x, ]) => x},
    {"name": "typeMatch", "symbols": ["typeMatch$macrocall$1", "typeMatch$macrocall$3", "expr"]},
    {"name": "listOpt", "symbols": []},
    {"name": "listOpt$ebnf$1", "symbols": []},
    {"name": "listOpt$ebnf$1$subexpression$1$macrocall$2", "symbols": [{"literal":","}]},
    {"name": "listOpt$ebnf$1$subexpression$1$macrocall$1", "symbols": ["listOpt$ebnf$1$subexpression$1$macrocall$2"], "postprocess": id},
    {"name": "listOpt$ebnf$1$subexpression$1$macrocall$1", "symbols": ["listOpt$ebnf$1$subexpression$1$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "listOpt$ebnf$1$subexpression$1", "symbols": ["listOpt$ebnf$1$subexpression$1$macrocall$1", "expr"]},
    {"name": "listOpt$ebnf$1", "symbols": ["listOpt$ebnf$1", "listOpt$ebnf$1$subexpression$1"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "listOpt", "symbols": ["expr", "listOpt$ebnf$1", "listRestOpt"]},
    {"name": "listRestOpt", "symbols": []},
    {"name": "listRestOpt$macrocall$2", "symbols": [{"literal":","}]},
    {"name": "listRestOpt$macrocall$1", "symbols": ["listRestOpt$macrocall$2"], "postprocess": id},
    {"name": "listRestOpt$macrocall$1", "symbols": ["listRestOpt$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "listRestOpt$macrocall$4", "symbols": [{"literal":"..."}]},
    {"name": "listRestOpt$macrocall$3", "symbols": ["listRestOpt$macrocall$4"], "postprocess": id},
    {"name": "listRestOpt$macrocall$3", "symbols": ["listRestOpt$macrocall$4", "_"], "postprocess": ([x, ]) => x},
    {"name": "listRestOpt", "symbols": ["listRestOpt$macrocall$1", "listRestOpt$macrocall$3", "expr"]},
    {"name": "pattern", "symbols": ["var_pattern"]},
    {"name": "pattern", "symbols": ["pair_pattern"]},
    {"name": "pattern", "symbols": ["list_pattern"]},
    {"name": "var_pattern", "symbols": ["var"]},
    {"name": "pair_pattern$macrocall$2", "symbols": [{"literal":"("}]},
    {"name": "pair_pattern$macrocall$1", "symbols": ["pair_pattern$macrocall$2"], "postprocess": id},
    {"name": "pair_pattern$macrocall$1", "symbols": ["pair_pattern$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "pair_pattern$macrocall$4", "symbols": [{"literal":","}]},
    {"name": "pair_pattern$macrocall$3", "symbols": ["pair_pattern$macrocall$4"], "postprocess": id},
    {"name": "pair_pattern$macrocall$3", "symbols": ["pair_pattern$macrocall$4", "_"], "postprocess": ([x, ]) => x},
    {"name": "pair_pattern$macrocall$6", "symbols": [{"literal":")"}]},
    {"name": "pair_pattern$macrocall$5", "symbols": ["pair_pattern$macrocall$6"], "postprocess": id},
    {"name": "pair_pattern$macrocall$5", "symbols": ["pair_pattern$macrocall$6", "_"], "postprocess": ([x, ]) => x},
    {"name": "pair_pattern", "symbols": ["pair_pattern$macrocall$1", "pattern", "pair_pattern$macrocall$3", "pattern", "pair_pattern$macrocall$5"]},
    {"name": "list_pattern$macrocall$2", "symbols": [{"literal":"["}]},
    {"name": "list_pattern$macrocall$1", "symbols": ["list_pattern$macrocall$2"], "postprocess": id},
    {"name": "list_pattern$macrocall$1", "symbols": ["list_pattern$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "list_pattern$macrocall$4", "symbols": [{"literal":"]"}]},
    {"name": "list_pattern$macrocall$3", "symbols": ["list_pattern$macrocall$4"], "postprocess": id},
    {"name": "list_pattern$macrocall$3", "symbols": ["list_pattern$macrocall$4", "_"], "postprocess": ([x, ]) => x},
    {"name": "list_pattern", "symbols": ["list_pattern$macrocall$1", "listOpt_pattern", "list_pattern$macrocall$3"]},
    {"name": "listOpt_pattern", "symbols": []},
    {"name": "listOpt_pattern$ebnf$1", "symbols": []},
    {"name": "listOpt_pattern$ebnf$1$subexpression$1$macrocall$2", "symbols": [{"literal":","}]},
    {"name": "listOpt_pattern$ebnf$1$subexpression$1$macrocall$1", "symbols": ["listOpt_pattern$ebnf$1$subexpression$1$macrocall$2"], "postprocess": id},
    {"name": "listOpt_pattern$ebnf$1$subexpression$1$macrocall$1", "symbols": ["listOpt_pattern$ebnf$1$subexpression$1$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "listOpt_pattern$ebnf$1$subexpression$1", "symbols": ["listOpt_pattern$ebnf$1$subexpression$1$macrocall$1", "pattern"]},
    {"name": "listOpt_pattern$ebnf$1", "symbols": ["listOpt_pattern$ebnf$1", "listOpt_pattern$ebnf$1$subexpression$1"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "listOpt_pattern", "symbols": ["pattern", "listOpt_pattern$ebnf$1", "listRestOpt_pattern"]},
    {"name": "listRestOpt_pattern", "symbols": []},
    {"name": "listRestOpt_pattern$macrocall$2", "symbols": [{"literal":","}]},
    {"name": "listRestOpt_pattern$macrocall$1", "symbols": ["listRestOpt_pattern$macrocall$2"], "postprocess": id},
    {"name": "listRestOpt_pattern$macrocall$1", "symbols": ["listRestOpt_pattern$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "listRestOpt_pattern$macrocall$4", "symbols": [{"literal":"..."}]},
    {"name": "listRestOpt_pattern$macrocall$3", "symbols": ["listRestOpt_pattern$macrocall$4"], "postprocess": id},
    {"name": "listRestOpt_pattern$macrocall$3", "symbols": ["listRestOpt_pattern$macrocall$4", "_"], "postprocess": ([x, ]) => x},
    {"name": "listRestOpt_pattern", "symbols": ["listRestOpt_pattern$macrocall$1", "listRestOpt_pattern$macrocall$3", "pattern"]},
    {"name": "compareOp$macrocall$2", "symbols": [(lexer.has("compareOp") ? {type: "compareOp"} : compareOp)]},
    {"name": "compareOp$macrocall$1", "symbols": ["compareOp$macrocall$2"], "postprocess": id},
    {"name": "compareOp$macrocall$1", "symbols": ["compareOp$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "compareOp", "symbols": ["compareOp$macrocall$1"], "postprocess": id},
    {"name": "exponentOp$macrocall$2", "symbols": [(lexer.has("exponentOp") ? {type: "exponentOp"} : exponentOp)]},
    {"name": "exponentOp$macrocall$1", "symbols": ["exponentOp$macrocall$2"], "postprocess": id},
    {"name": "exponentOp$macrocall$1", "symbols": ["exponentOp$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "exponentOp", "symbols": ["exponentOp$macrocall$1"], "postprocess": id},
    {"name": "productOp$macrocall$2", "symbols": [(lexer.has("productOp") ? {type: "productOp"} : productOp)]},
    {"name": "productOp$macrocall$1", "symbols": ["productOp$macrocall$2"], "postprocess": id},
    {"name": "productOp$macrocall$1", "symbols": ["productOp$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "productOp", "symbols": ["productOp$macrocall$1"], "postprocess": id},
    {"name": "sumOp$macrocall$2", "symbols": [(lexer.has("sumOp") ? {type: "sumOp"} : sumOp)]},
    {"name": "sumOp$macrocall$1", "symbols": ["sumOp$macrocall$2"], "postprocess": id},
    {"name": "sumOp$macrocall$1", "symbols": ["sumOp$macrocall$2", "_"], "postprocess": ([x, ]) => x},
    {"name": "sumOp", "symbols": ["sumOp$macrocall$1"], "postprocess": id}
];

export var ParserStart: string = "rootExpr";
