name: build

on: [workflow_call]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, macOS-14]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
    - name: enable-glob
      run: |
        shopt -s extglob nullglob globstar
      if: runner.os == 'Linux'
    - name: cache PureScript dependencies
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
        path: |
          fluid/.spago
          fluid/output
    - name: configure NPM authentication
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
    - name: test
      run: |
        yarn install
        set -x -e
        yarn workspace @explorable-viz/fluid tidy
        yarn workspace @explorable-viz/fluid build-test
