name: build

on: [workflow_call]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, macOS-14]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
          node-version: 22
    - name: enable-glob
      run: |
        shopt -s extglob nullglob globstar
      if: runner.os == 'Linux'
    - name: test
      run: |
        yarn install
        set -x -e
        yarn purs-tidy check src/**/*.purs test/**/*.purs
        yarn build-app
        yarn build-puppeteer
        yarn test-all
