name: deploy

on:
  push:
    paths-ignore:
    - 'old/**'
    - '**.md'
  pull_request:
    paths-ignore:
    - 'old/**'
    - '**.md'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy-fluid-org:
    runs-on: ubuntu-22.04
    needs: build
    if: github.ref == 'refs/heads/staging'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: build
      run: |
        yarn install
        yarn workspace @explorable-viz/fluid build
        yarn workspace fluid-org build
    - name: gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: website/fluid-org/build
        keep_files: false
