name: deploy

on:
  push:
    paths-ignore:
    - 'old/**'
    - '**.md'
  pull_request:
    paths-ignore:
    - 'old/**'
    - '**.md'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy-npm:
    runs-on: ubuntu-22.04
    needs: build
    if: github.ref == 'refs/heads/release'
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: 'https://registry.npmjs.org'
    - run: |
        yarn npm-publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy-gh-pages:
    runs-on: ubuntu-22.04
    needs: deploy-npm
    if: github.ref == 'refs/heads/release'
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        yarn install
        yarn build-app
    - name: gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/app/
        keep_files: true

  deploy-ESOP-artifact:
    runs-on: ubuntu-22.04
    needs: build
    if: github.ref == 'refs/heads/develop' && github.repository == 'rolyp/esop25-web-artifact'
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        yarn install
        yarn build-ESOP-artifact
    - name: gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/app/
        keep_files: false
