name: test-esop2025-artifact

on: [workflow_dispatch]

jobs:
  # test an approximation of the instructions submitted to the ESOP 2025 AE process
  verify-artifact-evaluation-instructions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Downloading and connecting to Docker image
      run: |
        set +x
        wget "https://zenodo.org/records/14626987/files/esop-artifact.tar.gz?download=1" -O esop-artifact.tar.gz
        gunzip esop-artifact.tar.gz
        docker load -i esop-artifact.tar
        docker run -d \
          --name esop-container \
          -p 8080:8080 \
          esop-artifact \
          tail -f /dev/null
    - name: Testing the installation
      # can't run test-all without fixing "No usable sandbox!" problem
      run: |
        docker exec esop-container bash -c "yarn test"
    - name: Reproducing tables in Section 5
      run: |
        docker exec esop-container bash -c "yarn benchmark"
      # TODO: Reproducing figures in Section 2
